---
 - name: transfer a file to remote host
   hosts: testgroup
   
   tasks:
       - name: copy file to remote host
         copy: 
            src: /etc/ansible/playbooks/somefile.txt
            dest: /tmp
            owner: jay
            group: jay
            mode: 0644
